### ISSUE TITLE
Port to osx

### ISSUE THREAD

**Issue by ice1x** [pmus/yukon#1]
Hi there!

I would like to try to port it to osx,
should it be even be possible?

Здравствуйте,
хочу портировать ваше решение на мак,
как считаете - это возможно? Может сразу можете подсказать какие то подводные камни,
или более того, какие то веские причины, по которым это было бы невозможно.

**Comment by pmus** [comment]
Hi,
porting to mac may be complicated or mostly impossible due several reasons:
1. Yukon is using proprietary win32 dll library provided by broker (FINAM), so it can work only in Windows and russian broker FINAM.
2. Not sure what are your goals. If you could replace data source to, say, cryptocurrency JSON provider, then yes, you can build a working trade solution. But this is more than just porting.
3. Everything is better with Python 3. It was my fault to use Python 2.x for this project.
4. Also if I started Yukon today, I'd use PySide instead of PyQt and better charting library.

pls feel free to ask qusestions if need to.

**Comment by ice1x** [comment]
OK,

thank you very much for the quick response!
It's good info! Perhaps to test my skills i can for first try to port it on Python 3.

**Comment by pmus** [comment]
May I wish you good luck then.
